#pragma once

/* key matrix size */
#define MATRIX_ROWS 6
#define MATRIX_COLS 17
/* key matrix pins */
#define MATRIX_ROW_PINS { A6, A5, A4, A3, A2, A1 }
#define MATRIX_COL_PINS { A7, B0, B1, B10, B11, B12, B13, B14, B15, A8, A9, A10, A15, B3, B4, B5, B6 }
/* COL2ROW or ROW2COL */
#define DIODE_DIRECTION COL2ROW
#define WS2812_DI_PIN B8
#define RGB_MATRIX_LED_COUNT 101
#define WS2812_PWM_DRIVER PWMD4  // default: PWMD2
#define WS2812_PWM_CHANNEL 3  // default: 2
#define WS2812_DMA_STREAM STM32_DMA1_STREAM7  
#define WS2812_DMA_CHANNEL 7

#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_KEYPRESSES
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS